var ioemenus=false,ioeul=[null,null],ioestatus=[0,0],ioetimer=null,ioefadetime=null;
function ioe_createmenus(){if(document.getElementById){e_div=document.getElementById("ioemenu2");if(e_div!=null){path="https://msds.open.ac.uk/students/";if(document.cookie.indexOf("P14MENU=Y")>=0)path="http://csintra1.open.ac.uk/students/";if(window.ioe_rel!=undefined){if(ioe_rel==1)path="";if(ioe_rel==2)path="https://msds-acct.open.ac.uk/students/";if(ioe_rel==3)path="../"}if(ioe_numcrse>0){ioeul[0]=document.createElement("ul");lft=200;if(ioe_crsewidth>43)lft-=(ioe_crsewidth-43)*16;ioeul[0].style.cssText=
"width:"+ioe_crsewidth+"em;left:"+lft+"px;";e_div.appendChild(ioeul[0]);for(i=0;i<ioe_numcrse;i++)ioe_addmenuitem(ioeul[0],ioe_course[i]," "+ioe_crsetitle[i]+" ("+ioe_pres[i].substr(0,4)+")",path+"module.aspx?c="+ioe_course[i]+"_"+ioe_pres[i],ioe_crsetype[i]);ioe_crsemore&&ioe_addmenuitem(ioeul[0],null,"See all your modules \u203a",path+"module-list.aspx",4);ioe_addmenuitem(ioeul[0],"Choose your next module \u203a","",path+"next.aspx",1)}if(ioe_numqual>0){ioeul[1]=document.createElement("ul");lft=
279;if(ioe_qualwidth>43)lft-=(ioe_qualwidth-36)*16;ioeul[1].style.cssText="width:"+ioe_qualwidth+"em;left:"+lft+"px;";e_div.appendChild(ioeul[1]);for(i=0;i<ioe_numqual;i++)ioe_qualocc[i].length==1?ioe_addmenuitem(ioeul[1],null,ioe_qualtitle[i],path+"research.aspx?t="+ioe_qualocc[i],0):ioe_addmenuitem(ioeul[1],null,ioe_qualtitle[i],path+"qual.aspx?q="+ioe_qualocc[i],0);ioe_qualmore&&ioe_addmenuitem(ioeul[1],null,"See all your qualifications \u203a",path+"quallist.aspx",4)}for(i=0;i<2;i++)if(ioeul[i]!=
null){if(window.attachEvent){ioeul[i].attachEvent("onmouseover",ioe_keepalive);ioeul[i].attachEvent("onmouseout",ioe_hidemenu)}if(window.addEventListener){ioeul[i].addEventListener("mouseover",ioe_keepalive,false);ioeul[i].addEventListener("mouseout",ioe_hidemenu,false)}}if(ioe_numqual>0||ioe_numcrse>0)e_div.style.cssText="display:block";ioemenus=true}}}
function ioe_addmenuitem(a,c,f,d,e){var b=document.createElement("a");b.setAttribute("href",d);if(c)if(e==1&&c){d=document.createElement("strong");d.appendChild(document.createTextNode(c));b.appendChild(d)}else b.appendChild(document.createTextNode(c));b.appendChild(document.createTextNode(f));if(e==1||e==4)b.className="active";if(e==3)b.className="cancel";window.attachEvent&&b.attachEvent("onclick",ioe_hidemenu);window.addEventListener&&b.addEventListener("click",ioe_hidemenu,false);c=document.createElement("li");
c.appendChild(b);a.appendChild(c)}
function ioe_showmenu(a){if(ioemenus){n=-1;if(a==3)n=0;if(a==4)n=1;for(i=0;i<2;i++)if(ioeul[i]!=null)if(i!=n){if(ioestatus[i]==1){ioestatus[i]=201;ioefadetime=new Date}if(ioestatus[i]==101)ioefadetime=ioestatus[i]=0;if(ioestatus[i]==102){ioestatus[i]=203;ioefadetime=0}if(ioestatus[i]==103){ioestatus[i]=202;ioefadetime=0}if(ioestatus[i]>300)ioestatus[i]=201}else{if(ioestatus[i]==0){ioestatus[i]=101;ioefadetime=new Date}if(ioestatus[i]==201){ioestatus[i]=1;ioefadetime=0}if(ioestatus[i]==202){ioestatus[i]=
103;ioefadetime=0}if(ioestatus[i]==203||ioestatus[i]==204){ioestatus[i]=102;ioefadetime=0}if(ioestatus[i]>300)ioestatus[i]=1}ioe_process();ioetimer||(ioetimer=window.setInterval("ioe_process()",30))}}function ioe_hidemenu(){if(ioemenus){for(i=0;i<2;i++){if(ioestatus[i]==1)ioestatus[i]=301;if(ioestatus[i]==101)ioestatus[i]=0;if(ioestatus[i]==102)ioestatus[i]=203;if(ioestatus[i]==103)ioestatus[i]=202}ioe_process()}}
function ioe_keepalive(){if(ioemenus)for(i=0;i<2;i++)if(ioestatus[i]>300)ioestatus[i]=1}
function ioe_process(){var a=false;if(ioefadetime>0){dur=new Date-ioefadetime;if(dur>150)a=true}for(i=0;i<2;i++){if(a==true&&ioestatus[i]>100&&ioestatus[i]<110)ioestatus[i]=103;if(a==true&&ioestatus[i]>200&&ioestatus[i]<210)ioestatus[i]=204;if(ioestatus[i]==101){ioeul[i].style.visibility="visible";ioeul[i].style.opacity="0.33";ioeul[i].style.filter="alpha(opacity=33)";ioestatus[i]=102}else if(ioestatus[i]==102){ioeul[i].style.opacity="0.67";ioeul[i].style.filter="alpha(opacity=67)";ioestatus[i]=103}else if(ioestatus[i]==
103){ioeul[i].style.opacity="1.0";ioeul[i].style.filter="alpha(opacity=100)";ioestatus[i]=1;ioefadetime=0}else if(ioestatus[i]==201){ioeul[i].style.opacity="0.75";ioeul[i].style.filter="alpha(opacity=75)";ioestatus[i]=202}else if(ioestatus[i]==202){ioeul[i].style.opacity="0.50";ioeul[i].style.filter="alpha(opacity=50)";ioestatus[i]=203}else if(ioestatus[i]==203){ioeul[i].style.opacity="0.25";ioeul[i].style.filter="alpha(opacity=25)";ioestatus[i]=204}else if(ioestatus[i]==204){ioeul[i].style.visibility=
"hidden";ioefadetime=ioestatus[i]=0}else if(ioestatus[i]>300){ioestatus[i]++;if(ioestatus[i]==315){ioestatus[i]=201;ioefadetime=new Date}}}a=false;for(i=0;i<2;i++)if(ioestatus[i]!=0)a=true;if(a==false){ioetimer&&window.clearInterval(ioetimer);ioetimer=null}};
